version: "3.8"

# Compose preparado para:
# - build local (quando rodar `docker compose up --build`)
# - ou usar a imagem publicada no GHCR (quando já tiver sido pushada)
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: notification-node-rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    container_name: notification-node-mailhog
    ports:
      - "8025:8025"

  # API: se --build for usado, Compose irá construir a imagem localmente a partir do Dockerfile.
  # Caso contrário, o Compose tentará puxar a imagem ghcr.io/migue/notification-node:latest.
  notification-node:
    image: ghcr.io/migue/notification-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-node-api
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_QUEUE=notifications
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - EMAIL_FROM=no-reply@example.com

  # Worker: usa mesma imagem; se for build local, será a mesma imagem construída acima.
  notification-worker:
    image: ghcr.io/migue/notification-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-node-worker
    command: npm run worker
    depends_on:
      - rabbitmq
      - mailhog

volumes:
  rabbitmq-data: