name: CI/CD Pipeline - Node.js & Docker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build (Instalar dependências)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar script de build (se presente)
        run: |
          if npm run | sed -n '1,200p' | grep -q "build"; then
            npm run build
          else
            echo "Nenhum script de build encontrado"
          fi

  publish:
    name: Publicar artefatos (opcional)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Coletar artefatos do build
        run: |
          if npm run | sed -n '1,200p' | grep -q "build"; then
            npm run build
          else
            echo "Nenhum script de build definido"
          fi

      # Opcional: publicar artefatos para uso entre jobs
      - name: Fazer upload dos artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            ./dist
            ./build
          if-no-files-found: ignore

  docker:
    name: Build e push da imagem Docker para GHCR
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fazer login no GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definir variável de repositório em minúsculas
        run: echo "IMAGE_NAME=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build e push da imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}/notification-node:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}/notification-node:latest
