name: CI/CD Pipeline - Node.js & Docker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build (Install dependencies)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run build script (if present)
        run: |
          if npm run | sed -n '1,200p' | grep -q "build"; then
            npm run build
          else
            echo "No build script found"
          fi

  publish:
    name: Publish build artifacts (optional)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Collect build artifacts
        run: |
          if npm run | sed -n '1,200p' | grep -q "build"; then
            npm run build
          else
            echo "No build script defined"
          fi

      # Opcional: publicar artefatos para uso entre jobs
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            ./dist
            ./build
          if-no-files-found: ignore

  docker:
    name: Docker build & push to GHCR
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/notification-node:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/notification-node:latest
