name: CI/CD Pipeline - Node.js

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build (Instalar dependências)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar script de build (se presente)
        run: |
          if npm run | sed -n '1,200p' | grep -q "build"; then
            npm run build
          else
            echo "Nenhum script de build encontrado"
          fi

  publish:
    name: Publicar artefatos (opcional)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Coletar artefatos do build
        run: |
          if npm run | sed -n '1,200p' | grep -q "build"; then
            npm run build
          else
            echo "Nenhum script de build definido"
          fi

      # Opcional: publicar artefatos para uso entre jobs
      - name: Fazer upload dos artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            ./dist
            ./build
          if-no-files-found: ignore
